server:
  port: 9910

spring:
  application:
    name: blog-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://openxm.cn:3306/openxm
    username: ${DATA_SOURCE_USER_NAME}
    password: ${DATA_SOURCE_USER_PASSWORD}

dubbo:
  application:
    name: blog-user
  protocol:
    name: dubbo
    port: 9911
  scan:
    base-packages: cn.openxm.bloguser.service.impl
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos

