server:
  port: 9910
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: blog-user
  mvc:
    servlet:
      path: /openxm/api/v1
  # TODO: 连接池未进行配置。
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://openxm.cn:3306/openxm
    username: ${DATA_SOURCE_USER_NAME}
    password: ${DATA_SOURCE_USER_PASSWORD}
  data:
    redis:
      host: openxm.cn
      port: 6379
      client-type: lettuce
      password: ${DATA_REDIS_PASSWORD}
      database: 1
      timeout: 10000                        # 数据读取超时时间。
      connect-timeout: 10                   # 连接超时时间。
      lettuce:
        pool:
          enabled: true
          max-active: 15                    # Redis Lettuce最大链接数量，当超过最大链接数量时，则会执行max-wait最大等待时间。
          max-idle: 10                       # Redis Lettuce 最大空闲链接数
          min-idle: 2                       # Redis Lettuce 最小空闲链接数
          max-wait: 10s                     # Redis Lettuce 连接池最大等待时间，当数量耗尽时，在最大等待时间内进行等待，超时之后抛出异常。
          time-between-eviction-runs: 60s   # Redis Lettuce 空闲链接最这个时间内如果未被启用则会Close

  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    username: 2280480546@qq.com
    password: ${MAIL_USER_PASSWORD_CODE}
    test-connection: true

dubbo:
  application:
    name: blog-user
  protocol:
    name: dubbo
    port: 19910
  scan:
    base-packages: cn.openxm.bloguser.application.rpc
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos

openxm:
  auth:
    jwt:
      secret: openxmcnuuuuiiijjjkkkllxxx
      expiration: 259200L # 3 day.
      tokenhead: 'Bearer '
      tokenheader: Authorization

# 日志配置。
logging:
  level:
    root: info


# mybatis 相关配置
mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml

email:
  user:
    from:
      addr: 2280480546@qq.com
