server:
  port: 9910

spring:
  application:
    name: blog-user
  mvc:
    servlet:
      path: /openxm/api/v1
  # TODO: 连接池未进行配置。
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://openxm.cn:3306/openxm
    username: ${DATA_SOURCE_USER_NAME}
    password: ${DATA_SOURCE_USER_PASSWORD}
  data:
    redis:
      host: openxm.cn
      port: 6379
      password: ${DATE_REDIS_PASSWORD}
      lettuce:
        pool:
          enabled: true
          max-active: 2                     # 连接池最大链接。
          min-idle: 1                       # 连接池 最小空闲链接。
          max-idle: 2                       # 最大空闲链接。
          max-wait: -1ms                    # 连接池最大阻塞时间。
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    username: 2280480546@qq.com
    password: ${MAIL_USER_PASSWORD_CODE}
    test-connection: true

dubbo:
  application:
    name: blog-user
  protocol:
    name: dubbo
    port: 19910
  scan:
    base-packages: cn.openxm.bloguser.application.rpc
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos


# mybatis 相关配置
mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml
